model_selection:
    model:
      XGBClassifier:
        search_param_grid:
          max_depth:
           - 5
          n_estimators:
           - 100
          random_state:
             - 0


      GaussianNB:
        search_param_grid:
          var_smoothing:
            - 0.05

      LogisticRegression:
        search_param_grid:
          C:
            - 1000
          max_iter:
            - 100
          penalty:
            - 'l2'
          solver:
            - 'liblinear'
